# Generated by Django 5.2.16 on 2026-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFAQCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(help_text='ID of the article in the Neon PostgreSQL articles table.', unique=True)),
                ('article_title', models.CharField(help_text='Stored so the frontend can display the title without hitting Neon again.', max_length=500)),
                ('content_hash', models.CharField(help_text='MD5 hex digest of (title + content). Cache is invalidated when this changes.', max_length=64)),
                ('faqs_json', models.TextField(help_text='JSON array: [{"question": "...", "answer": "..."}, ...]')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last LLM generation run for this article.')),
            ],
            options={
                'db_table': 'article_faq_cache',
                'ordering': ['article_id'],
            },
        ),
    ]
